### ISSUE TITLE
error on clumpify

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [c-guzman/cipher-workflow-platform#7]
I create a directory  for run the wrkflow:
I have this error:
```
nextflow run -qs 5 /home/centos/cipher-workflow-platform/cipher.nf --with-singularity /home/centos/cipher-workflow-platform/cipher.img --mode  chip --config  config.txt --fa /home/centos/reference_2/Hg38_genocode_prymary_kariotypic.fa --gtf  /home/centos/reference_2/gencode.v25.basic.annotation.gtf  --lib s --readLen 75 --macs_g hs --epic_gn hg38 --aligner bowtie2 --bamcoverage false --clumpify true

Sep-23 17:42:40.173 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Sep-23 17:42:40.175 [main] DEBUG nextflow.Session - >>> barrier register (process: multiqc)
Sep-23 17:42:40.179 [Task submitter] INFO  nextflow.Session - [12/e64d57] Submitted process > fetch_chrom_sizes
Sep-23 17:42:40.182 [Task submitter] INFO  nextflow.Session - [f4/b2763e] Submitted process > clumpify (2)
Sep-23 17:42:40.183 [Task submitter] INFO  nextflow.Session - [aa/35d79c] Submitted process > clumpify (4)
Sep-23 17:42:40.186 [Task submitter] INFO  nextflow.Session - [ca/7a51e1] Submitted process > create_mapping_index
Sep-23 17:42:40.187 [Task submitter] INFO  nextflow.Session - [bf/9ff2b7] Submitted process > clumpify (1)
Sep-23 17:42:40.191 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > multiqc -- maxForks: 16
Sep-23 17:42:40.220 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Sep-23 17:42:40.220 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Sep-23 17:42:40.221 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Sep-23 17:42:40.222 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 4; name: clumpify (2); status: COMPLETED; exit: 127; e
rror: -; workDir: /home/centos/PROVA/work/f4/b2763e74d2f23260126fb7c41a4fa3]
Sep-23 17:42:40.222 [main] DEBUG nextflow.Session - >>> barrier register (process: estimate_fragment_size)
Sep-23 17:42:40.224 [Task submitter] INFO  nextflow.Session - [59/13f32b] Submitted process > clumpify (3)
Sep-23 17:42:40.236 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > estimate_fragment_size -- maxForks: 16
Sep-23 17:42:40.263 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'clumpify (2)'

Caused by:
  Process `clumpify (2)` terminated with an error exit status (127)

Command executed:

  clumpify.sh -Xmx12g in=MB_HDAC_me3_S4_R1_001.fastq.gz out=HDAC27ac_S4_Rep2.clumped.fq.gz
  echo 'clumpify.sh -Xmx12g in=MB_HDAC_me3_S4_R1_001.fastq.gz out=HDAC27ac_S4_Rep2.clumped.fq.gz' > clumpify_parameters_HDAC27ac_S4_Rep2.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: clumpify.sh: command not found

Work dir:
  /home/centos/PROVA/work/f4/b2763e74d2f23260126fb7c41a4fa3

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
Sep-23 17:42:40.268 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `clumpify (2)` terminated with an error exit status (127)
Sep-23 17:42:40.306 [Task monitor] DEBUG nextflow.Session - Unexpected error dumping DGA status
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
```

**Comment by bioinfo-dirty-jobs** [comment]
Sorry wrong command:

`-with-singularity`

**Comment by c-guzman** [comment]
Did you get this to work using the correct command?

I know you managed to get this to work on the test dataset so you shouldn't be having this problem.

**Comment by bioinfo-dirty-jobs** [comment]
Sorry It was a wrong typing...
works great!!
